// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    /**
     * Migration usa conexão direta quando ela existe.
     *
     * O pooler do Supabase (porta 6543, PgBouncer em modo transação) não
     * suporta prepared statements nem advisory lock — `prisma migrate` trava
     * ou falha em cima dele. O app continua no pooler via `DATABASE_URL`; só
     * o CLI pega a direta.
     */
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
